// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CPPUtility
{
    internal sealed partial class Vsix
    {
        public const string Id = "CPPUtility.3bdb8c65-ff64-44aa-a42d-3cee0c0064f8";
        public const string Name = "CPPUtility";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.4.0";
        public const string Author = "晴彦 柴田";
        public const string Tags = "";
    }
}
