// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CPPUtility
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CPPUtilityString = "accbcd45-dcab-4d08-8da9-d1897dad0b56";
        public static Guid CPPUtility = new Guid(CPPUtilityString);

        public const string CPPUtilityOptionPageString = "7cef184d-42d9-4ea3-8b30-334ab3d3cc76";
        public static Guid CPPUtilityOptionPage = new Guid(CPPUtilityOptionPageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CPPUtilityMenuGroup = 0x0001;
        public const int CPPUtilityMenuSubGroup = 0x0002;
        public const int CPPUtilityMenu = 0x0010;
        public const int AutomaticallyAddConstCommand = 0x0100;
        public const int AutomaticallyAddConstIncludeTemplateCommand = 0x0101;
        public const int GenerateConstructorCommand = 0x0102;
        public const int EscapeCommand = 0x0103;
        public const int GenerateCPPComment = 0x0104;
        public const int CreateHeaderComment = 0x0105;
        public const int OpenOptionPageCommand = 0x0106;
        public const int FormatVariables = 0x0107;
    }
}